### ISSUE TITLE
안녕하세요 처음뵙겠습니다

### ISSUE THREAD

**Issue by Ejaeda** [T2SU/SDLShooter00#1]
이전 42서울 라피신 과정에서 T2SU님의 42SEOUL_Test를 통해 많은 도움을 받았습니다.

이 자리를 기회로 감사의 말씀을 드립니다.

라피신 과정이 끝난 이후에 당시 풀지 못했던 문제들을 마저 풀고 체점을 받아보고 싶은데요,

아직 테스트케이스를 가지고 계시다면 공유받을 수 있을지에 대해 문의차 연락드렸습니다.

뜬금없이 연락 드리게 되는 점, 그리고 개발공부를 시작한지 얼마 되지않아 제대로 된 방식으로 연락드리지 못해 죄송합니다.

**Comment by T2SU** [comment]
엇 이메일로 보내주셨어도 괜찮았어요 :D 
현재 해당 저장소가 비공개 상태입니다. 기여자 초대 해드릴게요!

**Comment by T2SU** [comment]
보컬팀에서 내려달라고 요청이 와서 내렸던거라.. ㅠㅠ 그리고 조금이나마 도움이 되셨다면 기쁩니다. :) 이슈... ㅋㅋㅋㅋ 너무 독특한 방법이라 놀람. 감사합니다 ☺️

**Comment by Ejaeda** [comment]
답장 감사드립니다!

이메일로 연락할 수 있었군요... 이슈를 잘 써보지않아 혹 해당 레포에 문제를 드리는건 아닌가 고민이 참 많았습니다.

텐시야님의 테스트케이스가 기존에 나와있는 테스트케이스 중 가장 좋은 케이스로 피시너들에게 소문이 나서 많은 피시너분들이 애용하고
있었습니다.

그러다 어느분께서 좋은 걸 함께 나누자는 마음으로 슬랙에 해당 레포를 올리게 되었고 이후 보컬팀 요청에 의해 비공개 하셧구나 짐작은
하구 있었습니다.

텐시야님의 테스트케이스가 많은 분들에게 큰 도움이 되었고 이 자리를 빌어 제가 대표로 감사의 마음을 전해드립니다 :)

이렇게 인사드리게 되어서 참 좋았네요.

 저도 텐시야님처럼 깃허브에서 누군가에게 도움되는 사람이 되기위해 노력하겠습니다. 고맙습니다!

2022년 2월 9일 (수) 오후 10:56, Tensiya ***@***.***>님이 작성:

**Comment by T2SU** [comment]
유용하게 사용해주셨던 분들이 계셨다면 더할 나위 없이 기쁘죠 🥰 
감사합니다!! 앞으로도 화이팅! 👏
